### ISSUE TITLE
Deregister Masternode

### ISSUE THREAD

**Issue by sionsmith** [firoorg/firo#1025]
**Describe the issue**

I have been running a masternode for around 3 years, the time has come to move on. I have searched high and low for a guide to deregister my node off the network and release my coins. However when attempting to send any number from the 1000 wallet I get the following "The amount exceeds your balance" I believe this is because the wallet has coin control enabled? How do I disable this on the new Firo Mac wallet?  don't have an options > settings there, is there a cli command I can run?

Has anyone gone through this process? Can anyone explain how this technically works? I'm happy to write a guide once i'm done.

**Can you reliably reproduce the issue?**
Yes

**What version of firo are you using?**
 v0.14.5.3

**Comment by justanwar** [comment]
You will first need to update to [Firo-QT v0.14.6.0,](https://github.com/firoorg/firo/releases/tag/v0.14.6.0) otherwise you can't connect to peers to send out your transaction. Because you updated late, you will need to do a [reindex of your wallet.](https://firo.org/guide/reindex-wallet.html)

**Do not proceed with the steps below if you are not on v0.14.6.0 AND on latest block.**

On MacOS, click on Preferences (in the top left menu bar) -> Options -> Wallet -> Enable coin control

In Send tab, click on ‘Use Transparent Balance’ in bottom right. Click on Inputs, choose the nodes you want to break, right-click and choose Unlock unspent. 

You should now be able to send out the coins for your masternode.

**Comment by ajaydono** [comment]
Please update your wallet to the latest first
https://github.com/firoorg/firo/releases/tag/v0.14.6.0

Since you have coin control enabled, Head to the transaction tab and click to the coin control to open the coin control window.

Find your collateral (1000firo) right click it and unlock it. 

Now you can spend it.
