### ISSUE TITLE
Allow different masternode ports

### ISSUE THREAD

**Issue by mksdev** [firoorg/firo#1170]
When trying to register master node on different port than default 8168 there is hardcoded check introduced in https://github.com/firoorg/firo/commit/8d54a4e33b069a9f3f95c4967742a158fe01318d which ends up in error if trying to use different one.
It would be nice to be able to run masternode on non-default port in case port is already taken by different service, or when running multiple masternodes behind one public ip.

Since all neccesary data is already stored on blockchain, it should be enough to just revert this commit (from my understanding by skimming through the codebase).

**Comment by skironDotNet** [comment]
They won't do it. They are CROWN developers and few orders (except PIVX) stick to this sick idea that if you just multiple MN on same VPS you threat the network on case you VPS goes down.
To me this is such a full of shit argument. I host 12 MNs of PIVX thanks to them allowing IPv6. If my VPS goes down then it maybe caused by data center going down and then we have same problem even if paid for 12 VPS with each single IPv4.

I think your argument is valid about port being taken but also invalid because what's on your server that the port is taken?
If you want to host multiple MNs from single VPS you should be using same port but different IP v6 (free and available)

Now to you developers. Forcing people to host from IPv4 is bigger threat than the bs one about VPS going down. 
Single FIRO instance takes 2.5GB of ram, so on 32GB ram you can host only 12 nodes. If they all go down let say due to server restart that's not a threat having other 4000 in the network. Now why ipv4 is bigger threat. Ipv4 is expensive, once the coin dumps in price it's not worth to host MN, this forces people to abandon the idea and then you really losing MNs.

Look at CRWN, hosting SN gives 50% APY but the coin is do cheap it can't pay for cheapest VPS. So my advice is allow IPv6 ASAP to make sure people will create nodes. The major cost of hosting is IP i can get 16GB RAM VPS from certain hosting company for $10 but only 2 IPv4 attached where 1st is free (part of vps cost) an the other cost 3 Euro a month. While i have whole /64 range of IPv6 addresses. So what's easier to host FIRO or PIVX?
Current price of FIRO $1.8 makes it bearly worth the cost + management time. So if it keeps dumping even current owner will sell their 1K of FIRO and you are gone

**Comment by mksdev** [comment]
I am not using any datacenter VPS, but running self hosted servers from multiple locations. It seems like everyone automatically assumes (even MN tutorials) that you go and rent VPS. When running master nodes from small office or home there is inherent problem that you generally cannot get IPv6 or multiple IPv4. 

Right now I am hosting 2 master nodes off one machine. Since the second master node can't use same IP I have wireguard VPN bridge to the second location where port is available. Does this improve decentralization or help with ISP going down? I don't think so. 

To run any number of master nodes I don't even need to buy VPS with enough resources for firod, just spawn wireguard instance for each masternode (which is much cheaper) and run VPN from the main server that can handle everything. This just artificially creates more points of failure than running multiple ports directly off one server. 

If this restriction is based only on fear of one VPS going down with 100 MNs than it's just lack of imagination of what you can do with little bit of docker.

**Comment by reubenyap** [comment]
@mksdev Hey yes the original concern was to discourage several masternodes from being hosted on a single instance/machine. Sure there are creative workarounds but it definitely makes it harder. Though we are trying to explore other ways to make home hosting more feasible, for most people a static IP is already a no go, so enabling additional masternode ports would be catering only to a small subset of people like yourself.

While @skironDotNet is right that we won't be protected in terms of datacentre outages, they are separate risks and if anything, this compounds it.

Also we don't have any relation to CROWN. AFAIK Dash still only allows IPv4 at this time and the [old technical discussion](https://github.com/dashpay/dash/pull/1065) still applies here. I believe we're still at 40% IPv6 adoption today.

**Comment by skironDotNet** [comment]
@reubenyap re: "I believe we're still at 40% IPv6 adoption today" but FIRO does not allow masternodes over IPv6 right?
