### ISSUE TITLE
Transaction to multiple receivers shows multiple times

### ISSUE THREAD

**Issue by nrsimha** [firoorg/firo#1287]
### Describe the issue

When sending transaction to multiple receivers after sending it shows in Transactions table multiple times.
If I make transaction to 2 receivers it shows in that table 2 times, if I send to n receivers it shows n-times same transaction.

It is display issue as right amount of Firo is sent. But it can bring panic/confusion as it looks like Firo has been sent n-times.

### Local setup

OS: Macos Ventura 13.4.1 (22F82)
Firo QT: Firo Core version v0.14.12.4-g0f292f6f0 (64-bit)

### Any extra information that might be useful in the debugging process.

This is video of the process:

https://github.com/firoorg/firo/assets/2452933/3f3c7dfd-1949-4b77-9fce-7541753031da

**Comment by justanwar** [comment]
Reproducible.

**Comment by levonpetrosyan93** [comment]
The correct behavior is following.
If there are multiple receivers, it shows a row for each receiver,
It should show the amount sent to corresponding to that receiver, so the issue is that is shows the amount spent in whale transaction,
Also it should show the receiver address, the issue #1299 is about that.
