### ISSUE TITLE
Github Actions needs to be updated

### ISSUE THREAD

**Issue by justanwar** [firoorg/firo#1459]
`actions/upload-artifact` v1 and v2 will be deprecated on 30 June 2024, v3 will be deprecated 30 November 2024. 

`actions/checkout` also needs to be updated.

https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by erciccione** [comment]
Started to look into this today. The problems appear with `upload-artifact` and `download-artifact`. Probably because multiple uploads of artifacts and overwriting an artifacts became more complicated. I [found a migration doc](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#overwriting-an-artifact) that should be helpful.

Input from people familiar with the firo CI environment would be very helpful.
