### ISSUE TITLE
Dockerfile in master branch differs from the layers found in the dockerhub latest tag

### ISSUE THREAD

**Issue by NorseGaud** [firoorg/firo#825]
When looking at the DockerHub Digest for `zcoinofficial/zcoind:latest`, I see that the ENTRYPOINT differs from what the master branch's Dockerfile is showing...

Dockerhub Digest: `ENTRYPOINT ["/bin/zcoind" "-printtoconsole"]`
Dockerfile: `ENTRYPOINT [ "/usr/bin/zcoind" ]`

What is used to generate the tags in dockerhub?

**Comment by ultimaweapon** [comment]
Nice one for noticing this!

Yes, we did not use the one that is in the root of the repository for the current version. The reason is that the image will be so big (about 1 GB). So we decided to just put the release binary into the image instead. Here is its source:

```
FROM ubuntu:18.04

COPY zcoin-* /

RUN useradd -m -U zcoind
USER zcoind

WORKDIR /home/zcoind

ENTRYPOINT ["/bin/zcoind", "-printtoconsole"]
```

**Comment by NorseGaud** [comment]
Thanks! I might want to eventually run my own image of zcoin for security reasons. This is helpful. Though I wonder what's using all of that space and whether it can be cleaned up or not.

**Comment by ultimaweapon** [comment]
The reason it takes a lot of space because our `Dockerfile` is not compact the image layers. Even though we remove the required packages in the last step but in reality, it does not remove those files from the previous layer. Even though we know how to fix it but currently we don't have enough resources to work on this.
