### ISSUE TITLE
Sigma spend creation with input value higher than 500XZC

### ISSUE THREAD

**Issue by flo071** [firoorg/firo#871]
### Describe the issue

Sigma spend inputs higher than 500XZC possible.

#### If so, please list the steps to reproduce below:
1. Get more than 500XZC minted
2. Wait for confirmations
3. Go to Sigma spend tab
4. Open coin control
5. Select all sigma mint inputs
6. Fill in spend receipent (amount must be blow 500XZC)
7. Confirm the spend

### Expected behaviour
Tell us that the transaction cannot be brodcaster/created (should not be allowed)

### Actual behaviour
Transaction gets added to the wallet, but cannot be broadcasted. Also when trying to abandon the TX this happens: 
zcoin-qt: wallet/wallet.cpp:1348: bool CWallet::AbandonTransaction(const uint256&): Zusicherung »wtx.tx->vin.size() == 1« nicht erfüllt.

### What version of bitcoin-core are you using?
v0.14.0.0-50822bad6

### Machine specs:
- OS: Ubuntu 18.04
- CPU: AMD Ryzen 7 1700
- RAM: 24GB
- Disk size: 2TB
- Disk Type (HD/SDD): SSD

**Comment by psolstice** [comment]
You shouldn't be able to create such transaction in the first place. You're right, the bug is we don't give correct error message in this case
There is a limit of 500 XZC for spending in single transaction. By using coin control you force more than 500 to be spent. Creation succeeds (bug) but the result can't be broadcast or enter the mempool (correct behavior).

**Comment by reubenyap** [comment]
Reopen if still an issue as Sigma should be now deprecated.
